---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    mintel.com/dex-k8s-ingress-watcher-client-id: ingress-kube-auth-multi-uri
    mintel.com/dex-k8s-ingress-watcher-redirect-uri: https://ingress.kube-auth.svc.cluster.local/oauth/callback,https://ingress.kube-auth.svc.cluster.local/oauth/callbackV2
    mintel.com/dex-k8s-ingress-watcher-secret: ingress-kube-auth-multi-uri
  labels:
    name: example-multi-uri
  name: example-multi-uri
  namespace: kube-auth
spec:
  rules:
    - host: ingress-multi-uri.kube-auth.svc.cluster.local
      http:
        paths:
          - backend:
              service:
                name: missing-service
                port:
                  number: 8080
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - ingress-multi-uri.kube-auth.svc.cluster.local
