---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    mintel.com/dex-k8s-ingress-watcher-client-id: ingress-kube-auth
    mintel.com/dex-k8s-ingress-watcher-redirect-uri: https://ingress.kube-auth.svc.cluster.local/oauth/callback
    mintel.com/dex-k8s-ingress-watcher-secret: ingress-kube-auth
  labels:
    name: example
  name: example
  namespace: kube-auth
spec:
  rules:
    - host: ingress.kube-auth.svc.cluster.local
      http:
        paths:
          - backend:
              service:
                name: missing-service
                port:
                  number: 8080
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - ingress.kube-auth.svc.cluster.local
