apiVersion: v1
kind: Secret
metadata:
  name: secret-with-annotations-and-labels
  namespace: default
  annotations:
    mintel.com/dex-k8s-ingress-watcher-client-id: secret-default
    mintel.com/dex-k8s-ingress-watcher-redirect-uri: https://secret.default.svc.cluster.local/oauth/callback
    mintel.com/dex-k8s-ingress-watcher-secret: secret-default
  labels:
    mintel.com/dex-k8s-ingress-watcher: enabled
