name: e2e

on:
#  push:
#    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  kind:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_image: 
          - "kindest/node:v1.19.1"
          - "kindest/node:v1.20.15"
          - "kindest/node:v1.21.10"
          - "kindest/node:v1.22.7"
          - "kindest/node:v1.23.5"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Kind Cluster
      uses: helm/kind-action@v1.2.0
      with:
        version: v0.12.0
        node_image: ${{ matrix.node_image }}
        cluster_name: kind
  
    - name: Build Container locally
      run: make docker VERSION=test
  
    - name: Wait for k8s
      run: |
        kubectl rollout status -n kube-system daemonset kindnet --timeout=180s
        kubectl rollout status -n kube-system daemonset kube-proxy --timeout=180s
        kubectl rollout status -n kube-system deployment coredns --timeout=180s

    - name: Run Acceptance Test
      run: |
        kind load docker-image mintel/dex-k8s-ingress-watcher:test
        hack/test-kind-dex.sh
